[project]
name = "tutorial-langchain"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "ipykernel>=7.0.1",
    "openai>=2.5.0",
    "python-dotenv>=1.1.1",
    "tiktoken==0.7.0",
]
